In [38]:
import pandas as pd

In [39]:
car_data = pd.read_csv("car_price_prediction_.csv")

In [40]:
print(type(car_data))

<class 'pandas.core.frame.DataFrame'>

In [41]:
car_data.head(10)

,Car ID,Brand,Year,Engine Size,Fuel Type,Transmission,Mileage,Condition,Price,Model
0,1,Tesla,2016,2.3,Petrol,Manual,114832,New,26613.92,Model X
1,2,BMW,2018,4.4,Electric,Manual,143190,Used,14679.61,5 Series
2,3,Audi,2013,4.5,Electric,Manual,181601,New,44402.61,A4
3,4,Tesla,2011,4.1,Diesel,Automatic,68682,New,86374.33,Model Y
4,5,Ford,2009,2.6,Diesel,Manual,223009,Like New,73577.10,Mustang
5,6,Audi,2019,2.4,Diesel,Automatic,246553,Like New,88969.76,Q7
6,7,Audi,2020,4.0,Electric,Automatic,135486,Used,63498.75,Q5
7,8,Tesla,2017,5.3,Hybrid,Automatic,83030,New,17381.19,Model Y
8,9,Honda,2023,5.7,Electric,Manual,120360,Like New,15905.62,Civic
9,10,Ford,2010,1.5,Electric,Automatic,135009,Like New,9560.22,Explorer

In [42]:
car_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Car ID        2500 non-null   int64
 1   Brand         2500 non-null   object
 2   Year          2500 non-null   int64
 3   Engine Size   2500 non-null   float64
 4   Fuel Type     2500 non-null   object
 5   Transmission  2500 non-null   object
 6   Mileage       2500 non-null   int64
 7   Condition     2500 non-null   object
 8   Price         2500 non-null   float64
 9   Model         2500 non-null   object
dtypes: float64(2), int64(3), object(5)
memory usage: 195.4+ KB

In [43]:
car_data = car_data.drop("Car ID" , axis = 1)

In [44]:
car_data.head(6)

,Brand,Year,Engine Size,Fuel Type,Transmission,Mileage,Condition,Price,Model
0,Tesla,2016,2.3,Petrol,Manual,114832,New,26613.92,Model X
1,BMW,2018,4.4,Electric,Manual,143190,Used,14679.61,5 Series
2,Audi,2013,4.5,Electric,Manual,181601,New,44402.61,A4
3,Tesla,2011,4.1,Diesel,Automatic,68682,New,86374.33,Model Y
4,Ford,2009,2.6,Diesel,Manual,223009,Like New,73577.10,Mustang
5,Audi,2019,2.4,Diesel,Automatic,246553,Like New,88969.76,Q7

In [45]:
car_data = pd.get_dummies(car_data, dtype=int)

In [25]:
car_data.head()

,Year,Engine Size,Mileage,Price,Brand_Audi,Brand_BMW,Brand_Ford,Brand_Honda,Brand_Mercedes,Brand_Tesla,...,Model_Model S,Model_Model X,Model_Model Y,Model_Mustang,Model_Prius,Model_Q5,Model_Q7,Model_RAV4,Model_X3,Model_X5
0,2016,2.3,114832,26613.92,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,0
1,2018,4.4,143190,14679.61,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2013,4.5,181601,44402.61,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2011,4.1,68682,86374.33,0,0,0,0,0,1,...,0,0,1,0,0,0,0,0,0,0
4,2009,2.6,223009,73577.10,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [46]:
y = car_data[["Price"]]
X = car_data.drop("Price",axis=1)

print("Target and Features successfully seperated")

Target and Features successfully seperated

In [52]:
print(X.columns)
print(y.columns)

Index(['Year', 'Engine Size', 'Mileage', 'Brand_Audi', 'Brand_BMW',
       'Brand_Ford', 'Brand_Honda', 'Brand_Mercedes', 'Brand_Tesla',
       'Brand_Toyota', 'Fuel Type_Diesel', 'Fuel Type_Electric',
       'Fuel Type_Hybrid', 'Fuel Type_Petrol', 'Transmission_Automatic',
       'Transmission_Manual', 'Condition_Like New', 'Condition_New',
       'Condition_Used', 'Model_3 Series', 'Model_5 Series', 'Model_A3',
       'Model_A4', 'Model_Accord', 'Model_C-Class', 'Model_CR-V',
       'Model_Camry', 'Model_Civic', 'Model_Corolla', 'Model_E-Class',
       'Model_Explorer', 'Model_Fiesta', 'Model_Fit', 'Model_Focus',
       'Model_GLA', 'Model_GLC', 'Model_Model 3', 'Model_Model S',
       'Model_Model X', 'Model_Model Y', 'Model_Mustang', 'Model_Prius',
       'Model_Q5', 'Model_Q7', 'Model_RAV4', 'Model_X3', 'Model_X5'],
      dtype='object')
Index(['Price'], dtype='object')

In [54]:

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("X_train columns:", X_train.columns)
print("y_train columns:", y_train.columns)

X_train columns: Index(['Year', 'Engine Size', 'Mileage', 'Brand_Audi', 'Brand_BMW',
       'Brand_Ford', 'Brand_Honda', 'Brand_Mercedes', 'Brand_Tesla',
       'Brand_Toyota', 'Fuel Type_Diesel', 'Fuel Type_Electric',
       'Fuel Type_Hybrid', 'Fuel Type_Petrol', 'Transmission_Automatic',
       'Transmission_Manual', 'Condition_Like New', 'Condition_New',
       'Condition_Used', 'Model_3 Series', 'Model_5 Series', 'Model_A3',
       'Model_A4', 'Model_Accord', 'Model_C-Class', 'Model_CR-V',
       'Model_Camry', 'Model_Civic', 'Model_Corolla', 'Model_E-Class',
       'Model_Explorer', 'Model_Fiesta', 'Model_Fit', 'Model_Focus',
       'Model_GLA', 'Model_GLC', 'Model_Model 3', 'Model_Model S',
       'Model_Model X', 'Model_Model Y', 'Model_Mustang', 'Model_Prius',
       'Model_Q5', 'Model_Q7', 'Model_RAV4', 'Model_X3', 'Model_X5'],
      dtype='object')
y_train columns: Index(['Price'], dtype='object')

In [55]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

print("Training complete! The model has learned the patterns.")

Training complete! The model has learned the patterns.

In [56]:
# Import our grading tool
from sklearn.metrics import mean_absolute_error

# 1. Ask the model to guess the prices for the test cars
predictions = model.predict(X_test)

# 2. Compare the model's guesses against the actual real prices (y_test)
error = mean_absolute_error(y_test, predictions)

print("On average, our model is off by: $", round(error, 2))

On average, our model is off by: $ 23877.14

In [63]:
# Take one existing car from the test set
my_car = X_test.iloc[[0]].copy()

# Change its mileage
my_car['Mileage'] = 150000

# Predict the price
my_prediction = model.predict(my_car)

print("The model predicts this car is worth: $", round(float(my_prediction[0]), 2))

The model predicts this car is worth: $ 55852.19

/tmp/ipykernel_1997/3891449290.py:10: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print("The model predicts this car is worth: $", round(float(my_prediction[0]), 2))

In [34]:
print(X_train.columns)

Index(['Price'], dtype='object')

In [35]:
print(X_test.columns)

Index(['Price'], dtype='object')

In [36]:
print(X_train.columns)

Index(['Price'], dtype='object')